## cicd/Jenkinsfile
```groovy
pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t my-app-image .'
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f deployment/deployment.yaml'
      }
    }
  }
}
```